from typing import Annotated, TypedDict

from pydantic import Field


class GraphState(TypedDict):
    """State shared across the graph."""

    question: Annotated[
        str,
        Field(description="The user's input question.")
    ]

    generation: Annotated[
        str,
        Field(description="The answer generated by the LLM.")
    ]

    web_search: Annotated[
        bool,
        Field(description="Whether a web search should be performed.")
    ]

    documents: Annotated[
        list[str],  
        Field(description="Relevant retrieved documents.")
    ]