from typing import Annotated, Optional, TypedDict
from operator import add


class ProfileCandidate(TypedDict):
    """A single candidate profile generated for a research query."""

    summary: str
    """Concise profile summary text."""

    full_report: str
    """Full research report content (from GPT Researcher)."""

    conclusion: str
    """Report conclusion, generated as a separate call — retryable independently."""

    sub_topics: list[str]
    """List of subtopics covered in the research report."""

    sources: list[str]
    """List of source URLs used to build this candidate."""

    research_sources: list[dict]
    """Richer source data: title, content, images per source — for internal citation checks."""

    costs: float
    """Token/credit cost of generating this candidate."""


class ResearchChainInput(TypedDict, total=False):
    """
    Input config for the research chain (conduct_research + build_report).
    Mirrors GPTResearcher's constructor + write_report parameters, kept
    separate from GraphState so chain calls stay swappable/testable
    independent of the graph.
    """

    query: str
    """The research query to run — required."""

    report_type: str
    """GPT Researcher report type, e.g. 'research_report', 'detailed_report'."""

    report_format: str
    """Citation/report format, e.g. 'APA'. Defaults to 'APA' if omitted."""

    tone: str
    """Tone instruction passed to GPTResearcher — defaults to Objective."""

    max_subtopics: int
    """Max number of subtopics to explore. Defaults to 5 if omitted."""

    verbose: bool
    """Verbose logging flag for the researcher run."""

    custom_prompt: Optional[str]
    """Prompt used for write_report — defaults to DEFAULT_PROFILE_PROMPT if omitted."""


class GraphState(TypedDict, total=False):
    """State shared across the graph."""

    user_initial_query: str
    """The user's original input query identifying the person/channel."""

    chain_input: ResearchChainInput
    """Resolved config passed into the research chain for the current run."""

    profile_candidates: list[ProfileCandidate]
    """Candidate profiles generated by GPT Researcher, for user selection."""

    selected_profile: Optional[ProfileCandidate]
    """The profile the user confirmed as accurate, once selected."""

    needs_more_research: bool
    """Whether the profile needs another research pass."""

    feedback_notes: Optional[str]
    """User's feedback explaining what was wrong or missing, if any."""

    research_iteration: int
    """Tracks how many research cycles have run — useful for capping retries."""